name: Publish develop image

on:
  push:
    branches:
      - master

jobs:
  publish-image:
    runs-on: ubuntu-latest
    name: Publish bundle and index images
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to container registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build bundle and index images and publish
        run: ./scripts/build-bundle-and-index.sh
